2019-12-29 18:32:40,077:INFO:measure_electricity_usage:Starting for environment development
2019-12-29 18:32:40,080:INFO:measure_electricity_usage:pid fiel in service
2019-12-29 18:32:40,085:INFO:measure_electricity_usage:<service._PIDFile object at 0x7f65177ac780>
2019-12-29 18:32:40,085:INFO:measure_electricity_usage:lalalalal
2019-12-29 18:32:40,085:DEBUG:measure_electricity_usage:>>>>>>>>>>>>>>>>service start
2019-12-29 18:32:40,086:DEBUG:measure_electricity_usage:found pid None
2019-12-29 18:32:40,086:DEBUG:PidFile:<pid.PidFile object at 0x7f6517790258> entering setup
2019-12-29 18:32:40,091:DEBUG:PidFile:<pid.PidFile object at 0x7f6517790258> create pidfile: /tmp/measure_electricity_usage.pid
2019-12-29 18:32:40,091:DEBUG:PidFile:<pid.PidFile object at 0x7f6517790258> check pidfile: /tmp/measure_electricity_usage.pid
2019-12-29 18:32:40,092:INFO:measure_electricity_usage:fh>>>>>>>>>>>>.
2019-12-29 18:32:40,092:INFO:measure_electricity_usage:<_io.TextIOWrapper name='/tmp/measure_electricity_usage.pid' mode='a+' encoding='UTF-8'>
2019-12-29 18:32:40,093:INFO:measure_electricity_usage:pid str>>>>>>>>>>>>.
2019-12-29 18:32:40,094:INFO:measure_electricity_usage:returning pid string
2019-12-29 18:32:40,095:DEBUG:PidFile:<pid.PidFile object at 0x7f6517790258> closing pidfile: None
2019-12-29 18:32:40,113:DEBUG:measure_electricity_usage:started
2019-12-29 18:32:40,114:ERROR:measure_electricity_usage:Exception ignored in:
2019-12-29 18:32:40,115:ERROR:measure_electricity_usage:<__main__.StreamToLogger object at 0x7f65177ac390>
2019-12-29 18:32:40,115:ERROR:measure_electricity_usage:AttributeError
2019-12-29 18:32:40,116:ERROR:measure_electricity_usage::
2019-12-29 18:32:40,116:ERROR:measure_electricity_usage:'StreamToLogger' object has no attribute 'flush'
2019-12-29 18:34:40,157:INFO:measure_electricity_usage:Starting for environment development
2019-12-29 18:34:44,681:INFO:measure_electricity_usage:pid fiel in service
2019-12-29 18:34:44,682:INFO:measure_electricity_usage:<service._PIDFile object at 0x7f3b37829588>
2019-12-29 18:34:44,683:INFO:measure_electricity_usage:lalalalal
2019-12-29 18:34:46,824:DEBUG:measure_electricity_usage:running>>>>>>>>>>>>>>>>.
2019-12-29 18:34:46,824:DEBUG:measure_electricity_usage:Searching for measurement devices configured in the db
2019-12-29 18:34:51,422:DEBUG:measure_electricity_usage:Found 1 measurement devices
2019-12-29 18:34:51,423:DEBUG:measure_electricity_usage:Found energy device device_1, adding it to scheduler
2019-12-29 18:34:51,805:INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
2019-12-29 18:34:51,808:INFO:apscheduler.scheduler:Added job "handle_measurement" to job store "default"
2019-12-29 18:34:51,809:INFO:apscheduler.scheduler:Scheduler started
2019-12-29 18:34:51,809:DEBUG:apscheduler.scheduler:Looking for jobs to run
2019-12-29 18:34:51,810:DEBUG:apscheduler.scheduler:Next wakeup is due at 2019-12-29 18:35:01.803398+01:00 (in 9.993463 seconds)
2019-12-29 18:35:01,804:DEBUG:apscheduler.scheduler:Looking for jobs to run
2019-12-29 18:35:01,812:DEBUG:apscheduler.scheduler:Next wakeup is due at 2019-12-29 18:35:11.803398+01:00 (in 9.998041 seconds)
2019-12-29 18:35:01,827:INFO:apscheduler.executors.default:Running job "handle_measurement (trigger: interval[0:00:10], next run at: 2019-12-29 18:35:11 CET)" (scheduled at 2019-12-29 18:35:01.803398+01:00)
2019-12-29 18:35:01,829:DEBUG:measure_electricity_usage:starting measure device_1
2019-12-29 18:35:01,831:DEBUG:nl.charging.services.EnergyUtil:Not production environment, getting fake data
2019-12-29 18:35:01,832:DEBUG:nl.charging.services.EnergyUtil:returning fake data
2019-12-29 18:35:01,834:DEBUG:measure_electricity_usage:Measurement returned {'energy_device_id': 'device_1', 'kwh_l1': 1532.34, 'kwh_l2': 1542.34, 'kwh_l3': 1534.34, 'a_l1': 534.34, 'a_l2': 534.34, 'a_l3': 534.34, 'kw_total': 50034.34}
2019-12-29 18:35:01,836:DEBUG:nl.carcharging.models.EnergyDeviceMeasureModel:Initializing EnergyDeviceMeasureModel with {'energy_device_id': 'device_1', 'kwh_l1': 1532.34, 'kwh_l2': 1542.34, 'kwh_l3': 1534.34, 'a_l1': 534.34, 'a_l2': 534.34, 'a_l3': 534.34, 'kw_total': 50034.34}
2019-12-29 18:35:01,865:ERROR:apscheduler.executors.default:Job "handle_measurement (trigger: interval[0:00:10], next run at: 2019-12-29 18:35:11 CET)" raised an exception
Traceback (most recent call last):
  File "/home/ilse/repos/RestfulCharging/venv/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/ilse/repos/RestfulCharging/src/nl/carcharging/daemon/MeasureElectricityUsage.py", line 127, in handle_measurement
    last_save_measurement = EnergyDeviceMeasureModel.get_last_one()
  File "/home/ilse/repos/RestfulCharging/src/nl/carcharging/models/EnergyDeviceMeasureModel.py", line 52, in get_last_one
    return session.query(EnergyDeviceMeasureModel)\
AttributeError: 'Query' object has no attribute 'order'
2019-12-29 18:35:07,151:ERROR:measure_electricity_usage:Traceback (most recent call last):
2019-12-29 18:35:07,153:ERROR:measure_electricity_usage:  File "/home/ilse/repos/RestfulCharging/src/nl/carcharging/daemon/MeasureElectricityUsage.py", line 202, in <module>
2019-12-29 18:35:07,153:ERROR:measure_electricity_usage:    main()
2019-12-29 18:35:07,154:ERROR:measure_electricity_usage:  File "/home/ilse/repos/RestfulCharging/src/nl/carcharging/daemon/MeasureElectricityUsage.py", line 185, in main
2019-12-29 18:35:07,156:ERROR:measure_electricity_usage:    service.run()
2019-12-29 18:35:07,159:ERROR:measure_electricity_usage:  File "/home/ilse/repos/RestfulCharging/src/nl/carcharging/daemon/MeasureElectricityUsage.py", line 96, in run
2019-12-29 18:35:07,160:ERROR:measure_electricity_usage:    self.create_save_measurement_jobs()
2019-12-29 18:35:07,160:ERROR:measure_electricity_usage:  File "/home/ilse/repos/RestfulCharging/src/nl/carcharging/daemon/MeasureElectricityUsage.py", line 111, in create_save_measurement_jobs
2019-12-29 18:35:07,161:ERROR:measure_electricity_usage:    scheduler.start()
2019-12-29 18:35:07,169:ERROR:measure_electricity_usage:  File "/home/ilse/repos/RestfulCharging/venv/lib/python3.6/site-packages/apscheduler/schedulers/blocking.py", line 19, in start
2019-12-29 18:35:07,170:ERROR:measure_electricity_usage:    self._main_loop()
2019-12-29 18:35:07,171:ERROR:measure_electricity_usage:  File "/home/ilse/repos/RestfulCharging/venv/lib/python3.6/site-packages/apscheduler/schedulers/blocking.py", line 28, in _main_loop
2019-12-29 18:35:07,176:ERROR:measure_electricity_usage:    self._event.wait(wait_seconds)
2019-12-29 18:35:07,177:ERROR:measure_electricity_usage:KeyboardInterrupt
2019-12-29 18:35:07,187:ERROR:measure_electricity_usage:Exception ignored in:
2019-12-29 18:35:07,188:ERROR:measure_electricity_usage:<__main__.StreamToLogger object at 0x7f3b382a7320>
2019-12-29 18:35:07,188:ERROR:measure_electricity_usage:AttributeError
2019-12-29 18:35:07,189:ERROR:measure_electricity_usage::
2019-12-29 18:35:07,190:ERROR:measure_electricity_usage:'StreamToLogger' object has no attribute 'flush'
